In [1]:
import numpy as np
import pandas as pd
import re
import nltk
import spacy
import string
pd.options.mode.chained_assignment = None
from sklearn import model_selection

In [2]:
full_df = pd.read_csv("hateval2019_en_train.csv")
df = full_df[["text"]]
df["text"] = df["text"].astype(str)
full_df.head()

id                                               text  HS  TR  AG
0  201  Hurray, saving us $$$ in so many ways @potus @...   1   0   0
1  202  Why would young fighting age men be the vast m...   1   0   0
2  203  @KamalaHarris Illegals Dump their Kids at the ...   1   0   0
3  204  NY Times: 'Nearly All White' States Pose 'an A...   0   0   0
4  205  Orban in Brussels: European leaders are ignori...   0   0   0

In [3]:
#***************************REMOVING USERNAME*************************************
import re

def remove_usernames_links(tweet):
    tweet = re.sub('@[^\s]+','',tweet)
    tweet = re.sub('http[^\s]+','',tweet)
    return tweet

df['tweet'] = df["text"].apply(remove_usernames_links)
df.head()

text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  
0  Hurray, saving us $$$ in so many ways   #LockT...  
1  Why would young fighting age men be the vast m...  
2   Illegals Dump their Kids at the border like R...  
3  NY Times: 'Nearly All White' States Pose 'an A...  
4  Orban in Brussels: European leaders are ignori...

In [4]:
#**********************Lower Case conversion*******************************************
df["text_lower"] = df["tweet"].str.lower()
df.head()

text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  
0  hurray, saving us $$$ in so many ways   #lockt...  
1  why would young fighting age men be the vast m...  
2   illegals dump their kids at the border like r...  
3  ny times: 'nearly all white' states pose 'an a...  
4  orban in brussels: european leaders are ignori...

In [5]:
#*****************************Remove Punctuation**********************************************
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["text_wo_punct"] = df['text_lower'].apply(lambda text: remove_punctuation(text))
df.head()

text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  \
0  hurray, saving us $$$ in so many ways   #lockt...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times: 'nearly all white' states pose 'an a...   
4  orban in brussels: european leaders are ignori...   

                                       text_wo_punct  
0  hurray saving us  in so many ways   lockthemup...  
1  why would young fighting age men be the vast m...  
2   illegals dump their kids at the border like r...  
3  ny times nearly all white states pose an array...  
4  orban in brussels european leaders are ignorin...

In [6]:
#*****************************************STOP WORDS ***********************************
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Sanghita
[nltk_data]     Chakraborty\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))


"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mus

In [8]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df["text_wo_stop"] = df["text_wo_punct"].apply(lambda text: remove_stopwords(text))
df.head()

text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  \
0  hurray, saving us $$$ in so many ways   #lockt...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times: 'nearly all white' states pose 'an a...   
4  orban in brussels: european leaders are ignori...   

                                       text_wo_punct  \
0  hurray saving us  in so many ways   lockthemup...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times nearly all white states pose an array...   
4  orban in brussels european leaders are ignorin...   

                                        text_wo_stop  
0  hurray saving us many ways lockthemup buildthe...  
1  would young fighting age men vast majority one...  
2  illegals dump kids border like road kill refus...  
3  ny times nearly white states pose array proble...  
4  orban brussels european leaders ignoring peopl...

In [9]:
#***********************************REMOVE URLS*****************************************
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [10]:
df["text_wo_urlno"] = df["text_wo_stop"].apply(lambda text: remove_urls(text))
df.head()

text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  \
0  hurray, saving us $$$ in so many ways   #lockt...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times: 'nearly all white' states pose 'an a...   
4  orban in brussels: european leaders are ignori...   

                                       text_wo_punct  \
0  hurray saving us  in so many ways   lockthemup...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times nearly all white states pose an array...   
4  orban in brussels european leaders are ignorin...   

                                        text_wo_stop  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                       text_wo_urlno  
0  hurray saving us many ways lockthemup buildthe...  
1  would young fighting age men vast majority one...  
2  illegals dump kids border like road kill refus...  
3  ny times nearly white states pose array proble...  
4  orban brussels european leaders ignoring peopl...

In [11]:
#*************************************REMOVAL OF HTML TAGS**********************************************
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

df["text_wo_htmlno"] = df["text_wo_urlno"].apply(lambda text: remove_html(text))
df.head()


text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  \
0  hurray, saving us $$$ in so many ways   #lockt...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times: 'nearly all white' states pose 'an a...   
4  orban in brussels: european leaders are ignori...   

                                       text_wo_punct  \
0  hurray saving us  in so many ways   lockthemup...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times nearly all white states pose an array...   
4  orban in brussels european leaders are ignorin...   

                                        text_wo_stop  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                       text_wo_urlno  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                      text_wo_htmlno  
0  hurray saving us many ways lockthemup buildthe...  
1  would young fighting age men vast majority one...  
2  illegals dump kids border like road kill refus...  
3  ny times nearly white states pose array proble...  
4  orban brussels european leaders ignoring peopl...

In [12]:
#*******************************LEMMATIZATION************************************
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV}
def lemmatize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])

df["text_lemmatized"] = df["text_wo_htmlno"].apply(lambda text: lemmatize_words(text))
df.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Sanghita
[nltk_data]     Chakraborty\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to C:\Users\Sanghita
[nltk_data]     Chakraborty\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


text  \
0  Hurray, saving us $$$ in so many ways @potus @...   
1  Why would young fighting age men be the vast m...   
2  @KamalaHarris Illegals Dump their Kids at the ...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                               tweet  \
0  Hurray, saving us $$$ in so many ways   #LockT...   
1  Why would young fighting age men be the vast m...   
2   Illegals Dump their Kids at the border like R...   
3  NY Times: 'Nearly All White' States Pose 'an A...   
4  Orban in Brussels: European leaders are ignori...   

                                          text_lower  \
0  hurray, saving us $$$ in so many ways   #lockt...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times: 'nearly all white' states pose 'an a...   
4  orban in brussels: european leaders are ignori...   

                                       text_wo_punct  \
0  hurray saving us  in so many ways   lockthemup...   
1  why would young fighting age men be the vast m...   
2   illegals dump their kids at the border like r...   
3  ny times nearly all white states pose an array...   
4  orban in brussels european leaders are ignorin...   

                                        text_wo_stop  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                       text_wo_urlno  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                      text_wo_htmlno  \
0  hurray saving us many ways lockthemup buildthe...   
1  would young fighting age men vast majority one...   
2  illegals dump kids border like road kill refus...   
3  ny times nearly white states pose array proble...   
4  orban brussels european leaders ignoring peopl...   

                                     text_lemmatized  
0  hurray save u many way lockthemup buildthewall...  
1  would young fight age men vast majority one es...  
2  illegals dump kid border like road kill refuse...  
3  ny time nearly white state pose array problem ...  
4  orban brussels european leader ignore people w...

In [13]:
input_text = df["text_lemmatized"]
print(input_text)
print(type(input_text))

0       hurray save u many way lockthemup buildthewall...
1       would young fight age men vast majority one es...
2       illegals dump kid border like road kill refuse...
3       ny time nearly white state pose array problem ...
4       orban brussels european leader ignore people w...
                              ...                        
8995                               proud hysterical woman
8996    hollywood complicit rape sexual assault woman ...
8997    fuck cunt hate see kid get neglect used parent...
8998                                hysterical woman like
8999    nearly every woman know metoo fee sexual harre...
Name: text_lemmatized, Length: 9000, dtype: object
<class 'pandas.core.series.Series'>


In [14]:
#input_text converted to list --- THIS IS NEEDED FOR FITTING
input_text = input_text.tolist()
print(input_text)
print(type(input_text))


['hurray save u many way lockthemup buildthewall enddaca boycottnfl boycottnike', 'would young fight age men vast majority one escape war amp cannot fight like woman child elderlyits majority refugees actually refugees economic migrant try get europe', 'illegals dump kid border like road kill refuse unite hope get amnesty free education welfare illegal familesbelongtogether country taxpayer dime scam nodaca noamnesty sendthe', 'ny time nearly white state pose array problem immigrant', 'orban brussels european leader ignore people want migrant', 'legal illegal buildthatwall', 'antifa pack druggie misfits one love violent thug cry attention hit self importancejuveniledelinquents', 'exteacher pleads guilty rape charge', 'still place bengali sylheti class london 2nd language know anyone interested', 'dfid africa regional profile july 2018', 'watch benjamin netanyahu back trump decision cut aid palestinian unrwa free speech time', 'illegals dump kid here get welfare aid u school rip u taxpa

In [15]:
Y = full_df.filter(['HS','TR','AG'])
print(Y)
print(type(Y))

      HS  TR  AG
0      1   0   0
1      1   0   0
2      1   0   0
3      0   0   0
4      0   0   0
...   ..  ..  ..
8995   0   0   0
8996   0   0   0
8997   1   1   1
8998   0   0   0
8999   0   0   0

[9000 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>


In [16]:
#train test split:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(input_text,Y,test_size=0.3)

In [17]:
print(Train_X)
print(Test_X)
print(type(Test_X))
print(type(Train_X))

['since love trial false equivalency athlete protect woman one duke lacrosse rape', 'feel buy round shot', 'happy 21st birthday slut🤘🏾🎂 already know on😈', 'aw 😍😘 owe mustache ride', 'stranger welcome difficult year u believe welcome refugee get easy anytime soon refugeeswelcome', 'fuck hoe bitch ain’t nothin woman trippin bruh', 'food send migrant ship sicily italy awaits eu asylum offer', 'iligal refugee go home kid', 'thank amp everyone else show yesterday shed light legal resource available help citys immigrant family', 'man shot good samaritan death daca recipient via enddaca noamnesty enforceuslawskeepamericanssafe', 'picture call useless fugly skank bitch', 'lol girl 😭😭 don’t want nobody kno baby bitch 😭😭', 'alternative headline illegal immigrant swallow heroin', 'absence favorable response govt possible displaced people attempt reoccupy land ucanews voiceforthevoiceless humanrights srilanka', 'today genuinely stupid bern whataboutism cant bitch guy say identity politics distract

In [18]:
print(Train_Y)
print(Test_Y)
print(type(Train_Y))
print(type(Test_Y))

      HS  TR  AG
6669   0   0   0
7470   0   0   0
4620   0   0   0
7182   0   0   0
4246   0   0   0
...   ..  ..  ..
2520   0   0   0
5712   1   0   0
2136   0   0   0
7669   0   0   0
751    0   0   0

[6300 rows x 3 columns]
      HS  TR  AG
3990   0   0   0
1065   0   0   0
5003   1   1   0
1025   1   0   0
5736   1   1   1
...   ..  ..  ..
7711   0   0   0
1376   0   0   0
52     0   0   0
1547   1   0   0
7023   0   0   0

[2700 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidfvectorizer = TfidfVectorizer(stop_words= 'english')

In [23]:
tfidfvectorizer.fit(input_text)

TfidfVectorizer(stop_words='english')

In [25]:
tfidf_wm_trainX = tfidfvectorizer.transform(Train_X)
tfidf_wm_testX = tfidfvectorizer.transform(Test_X)

In [26]:
print(tfidf_wm_trainX)


  (0, 15108)	0.13117650914828186
  (0, 14010)	0.3471452550309701
  (0, 11152)	0.17450383250318416
  (0, 10907)	0.2521054587000863
  (0, 8344)	0.21811051585782815
  (0, 7881)	0.40710869030949615
  (0, 5101)	0.31454125118141174
  (0, 4776)	0.40710869030949615
  (0, 4388)	0.40710869030949615
  (0, 1361)	0.35292108536243283
  (1, 12380)	0.5219424016740708
  (1, 11793)	0.5557688444395797
  (1, 5212)	0.42236838706953356
  (1, 2375)	0.4902061469313474
  (2, 12595)	0.34131650622452503
  (2, 7812)	0.292576979377043
  (2, 6231)	0.43611509555895484
  (2, 1870)	0.4905991013814919
  (2, 215)	0.6058200218435882
  (3, 11659)	0.42961897985311065
  (3, 10094)	0.47787284872138286
  (3, 9268)	0.5687643377020738
  (3, 1449)	0.5133928327929835
  (4, 15310)	0.21085513352062765
  (4, 14923)	0.4592880705683061
  :	:
  (6297, 2816)	0.19418772173962495
  (6297, 2427)	0.16187195121721557
  (6297, 2352)	0.25885789704088774
  (6297, 1028)	0.25885789704088774
  (6297, 1027)	0.25885789704088774
  (6297, 346)	0.23979

In [27]:
print(tfidf_wm_testX)

  (0, 13394)	0.2637600207992293
  (0, 10967)	0.3584155494307225
  (0, 7114)	0.38690970280423276
  (0, 6893)	0.15043079664963951
  (0, 6492)	0.38690970280423276
  (0, 5793)	0.28833612767761074
  (0, 5461)	0.2322928826384782
  (0, 5278)	0.2368370793281327
  (0, 4174)	0.38690970280423276
  (0, 3671)	0.31683028105112104
  (0, 993)	0.19149734049644923
  (1, 14055)	0.09543983384654564
  (1, 12981)	0.15617585617512633
  (1, 12130)	0.14913406669241475
  (1, 11325)	0.07405240776841503
  (1, 10498)	0.21702982750991356
  (1, 10493)	0.1343975344137013
  (1, 10273)	0.15788471045521857
  (1, 10141)	0.21702982750991356
  (1, 10138)	0.15536668611810214
  (1, 9316)	0.21702982750991356
  (1, 9315)	0.21702982750991356
  (1, 8936)	0.12705431605786188
  (1, 8170)	0.08323889340098575
  (1, 7455)	0.19590109744934675
  :	:
  (2697, 11492)	0.3734994649950855
  (2697, 10734)	0.3510007822599567
  (2697, 10529)	0.36893704597656246
  (2697, 9283)	0.31934018713345813
  (2697, 5689)	0.3259533289090198
  (2698, 13639

In [28]:
print(type(tfidf_wm_trainX))

<class 'scipy.sparse.csr.csr_matrix'>


In [29]:
view_tfidf_wm_trainX = tfidf_wm_trainX.toarray()
view_tfidf_wm_testX = tfidf_wm_testX.toarray()
print(view_tfidf_wm_trainX)
print(view_tfidf_wm_trainX)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [30]:
feature_names = tfidfvectorizer.get_feature_names()

In [31]:
print(feature_names)

['000s', '0045', '0062', '01', '040918', '047', '0827am', '0831', '10', '100', '1000', '10000', '100000', '1000000', '100000to', '10001', '1000month', '100100', '1004', '100th', '101', '1012', '1013', '1024', '1030', '104', '106', '107', '107000', '109', '10am', '10am4pm', '10cm', '10k', '10mins', '10mn', '10month', '10th', '10tv', '10y', '10yearold', '10yrs', '11', '11000', '110000', '1112', '111yearold', '1124', '1130', '114', '1159p', '1159pm', '1172', '118000', '11am', '11yearold', '11yrold', '12', '120', '1200', '12000', '120k', '121', '122ðÿ', '1230', '124', '125', '12690crs', '127', '12746', '12kyoto', '12p', '12yearold', '13', '130', '13000', '130000', '1325this', '135', '13785', '138', '13th', '13yearold', '13yr', '14', '1400', '14000', '1425', '14300', '14yearold', '15', '150', '1500', '15000', '150th', '1520', '153', '155', '15b', '15m', '15th', '15times', '15tn', '15yearold', '16', '160', '1600', '16000', '164', '1640', '166', '16gb', '16k', '16th', '16year', '16yearold', '

In [32]:
print(len(feature_names))

15450


In [ ]:
'''for col in tfidf_wm.nonzero()[1]:
    print(feature_names[col],'-',tfidf_wm[0,col])
'''